version: "3"

services:
    warc-reader-service:
        build: ./backend-warc-reader
        volumes:
            - ./backend-warc-reader:/app
        depends_on:
            - mongodb-service
            - elasticsearch-service
        networks:
            - shearwater
        environment:
            - DB_NAME=shearwater
            - MAX_RECORD_FETCH=50
    mongodb-service:
        image: mongo:4.0-xenial
        ports:
            - "27017:27017"
        restart: always
        command: --quiet
        networks:
            - shearwater
    kibana-service:
        image: kibana:6.8.2
        ports:
            - "5601:5601"
        restart: always
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch-service:9200
            - LOGGING_QUIET=true
        depends_on:
            - elasticsearch-service
        networks:
            - shearwater
    elasticsearch-service:
        image: elasticsearch:6.8.2
        environment:
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
            - "http.cors.allow-credentials=true"
        depends_on:
            - mongodb-service
        ports:
            - "9200:9200"
        restart: always
        command: ["elasticsearch", "-Elogger.level=ERROR"]
        networks:
            - shearwater

networks:
    shearwater:
